apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
type: Opaque
stringData:
  JWT_SECRET: "xxxxxxxxxxxxxxx"
  MONGO_URI: "xxxxxxxxxxxxxxxx"
  CLOUDINARY_API_KEY: "xxxxxxxx"
  CLOUDINARY_API_SECRET: "xxxxxxxx"
  SENDGRID_API_KEY: "xxxxxxxxx"
